#server:
#  port: 3388
#
#spring:
#  application:
#    name: pap-payment-service
#  cloud:
#    sentinel:
#      transport:
#        #配置Sentin dashboard地址
#        dashboard: localhost:8080
#        # 默认8719端口，假如被占用了会自动从8719端口+1进行扫描，直到找到未被占用的 端口
#        port: 8719
#
#config:
#  info: alipay is prepare
