server:
  port: 83

spring:
  profiles:
    active: dev


#spring:
#  application:
#    name: pap-gateway-server
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
#      routes: #路由配置
#        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名，这里匹配支付服务
#          #匹配后提供服务的路由地址
#          uri: lb://pap-payment-service
#          predicates:
#            - Path=/payment/** # 断言，路径相匹配的进行路由
#        - id: order_route # 路由的id,没有规定规则但要求唯一,建议配合服务名，这里匹配订单服务
#          #匹配后提供服务的路由地址
#          uri: lb://pap-order-service
#          predicates:
#            - Path=/order/** # 断言，order路径路由到订单服务



